### PR TITLE
move terminator address to seperate field

### PR DESCRIPTION
**Pull request by camotts**
https://github.com/openziti/ziti/issues/565

### CODE REVIEW

**Comment by camotts** [comment]
> I don't see a new field on the event. Am I missing something?

I might have misunderstood the intent here. I was under the impression we wanted to change the log only. I can go add it to the event as well.

**Comment by plorenz** [comment]
> > I don't see a new field on the event. Am I missing something?
> 
> I might have misunderstood the intent here. I was under the impression we wanted to change the log only. I can go add it to the event as well.

I think the main goal is to have the path and the address available in the event, just as separate fields.

**Comment by camotts** [comment]
> > > I don't see a new field on the event. Am I missing something?
> > 
> > 
> > I might have misunderstood the intent here. I was under the impression we wanted to change the log only. I can go add it to the event as well.
> 
> I think the main goal is to have the path and the address available in the event, just as separate fields.

Definitely misunderstood then! Will add that

**Review by plorenz — APPROVED** [review]

**Comment by plorenz** [comment]
Looks good :+1:

**Pull request merged**
